### ISSUE TITLE
Sniff traffic

### ISSUE THREAD

**Issue by neopaf** [RobotPajamas/Stetho-Couchbase#6]
Is it possible to add to Stetho the network exchange between Couchbase Lite and a Couchbase Sync Gateway?

(or maybe it is already there and I'm not initialising properly)

**Comment by sureshjoshi** [comment]
@neopaf Have you tried using the Stetho network helpers?
https://facebook.github.io/stetho/

Couchbase uses OKHttp3 if I recall correctly, so maybe this could work? 

    compile 'com.facebook.stetho:stetho-okhttp3:1.5.0'

**Comment by neopaf** [comment]
maybe! thanks for the pointer.

didn't do it (yet), outline (for guys who would google this up):
subclass `CouchbaseLiteHttpClientFactory`
in `getOkHttpClient` return `super.getOkHttpClient` with interceptor as https://github.com/facebook/stetho 
use `manager.setDefaultHttpClientFactory` to replace factory to this one.

**Comment by neopaf** [comment]
Suresh, I guess, this is not up to this issue, closing it.
